### ISSUE TITLE
Чтобы отсортировать ETH адреса по количеству денег в уменьшительном порядке?

### ISSUE THREAD

**Issue by scramby1337** [scramby1337/SCRIPT-THAT-HELP#1]
Чтобы отсортировать ETH адреса по количеству денег в уменьшительном порядке?

**Comment by scramby1337** [comment]
Чтобы отсортировать ETH адреса по количеству денег в уменьшительном порядке, выполните следующие шаги:

1. Выделите данные:
   - Выделите обе колонки (ETH адреса и сумму денег).

2. Перейдите в раздел "Данные":
   - Нажмите на вкладку Данные в верхнем меню Excel.

3. Сортировка:
   - Нажмите на кнопку Сортировка по убыванию (обычно это кнопка с изображением стрелки вниз).
   - Выберите, что именно вы хотите сортировать - выберите вторую колонку (количество денег).

4. Подтвердите:
   - Если появится окно с запросом на выбор диапазона для сортировки, убедитесь, что выбраны обе колонки, чтобы сохранить связь между адресами и суммами.

Теперь ваши ETH адреса будут отсортированы по количеству денег в уменьшительном порядке!

**Comment by ZenuAizak** [comment]
Чтобы отсортировать ETH адреса по количеству денег в уменьшительном порядке, выполните следующие шаги:

1. Выделите данные:
   - Выделите обе колонки (ETH адреса и сумму денег).

2. Перейдите в раздел "Данные":
   - Нажмите на вкладку Данные в верхнем меню Excel.

3. Сортировка:
   - Нажмите на кнопку Сортировка по убыванию (обычно это кнопка с изображением стрелки вниз).
   - Выберите, что именно вы хотите сортировать - выберите вторую колонку (количество денег).

4. Подтвердите:
   - Если появится окно с запросом на выбор диапазона для сортировки, убедитесь, что выбраны обе колонки, чтобы сохранить связь между адресами и суммами.

Теперь ваши ETH адреса будут отсортированы по количеству денег в уменьшительном порядке!

**Comment by scramby1337** [comment]
> Чтобы отсортировать ETH адреса по количеству денег в уменьшительном порядке, выполните следующие шаги:
> 
> 1. Выделите данные:
>    
>    * Выделите обе колонки (ETH адреса и сумму денег).
> 2. Перейдите в раздел "Данные":
>    
>    * Нажмите на вкладку Данные в верхнем меню Excel.
> 3. Сортировка:
>    
>    * Нажмите на кнопку Сортировка по убыванию (обычно это кнопка с изображением стрелки вниз).
>    * Выберите, что именно вы хотите сортировать - выберите вторую колонку (количество денег).
> 4. Подтвердите:
>    
>    * Если появится окно с запросом на выбор диапазона для сортировки, убедитесь, что выбраны обе колонки, чтобы сохранить связь между адресами и суммами.
> 
> Теперь ваши ETH адреса будут отсортированы по количеству денег в уменьшительном порядке!

thank you!
